@startuml


[*] --> STARTING
STARTING --> STARTED : SCRIPTLOADED
STARTING : Here we instantiate the Worker() object.

STARTED --> INITIALIZED : BASEINIT_COMPLETE
STARTED : We get a message back that the basethread script properly loaded.

INITIALIZED : This is where we load requirejs.
INITIALIZED : TODO Load any loading subsystem.


INITIALIZED --> DISPATCH

DISPATCH : This is where the execution
DISPATCH :  of the sided script occurs.

DISPATCH --> JOB
JOB --> COMPLETED
COMPLETED --> [*]

STARTING --> COMPLETED : Exception



@enduml
